MAIN_SRCS = glob(["*.py"])

py_binary(
    name = "main",
    srcs = [
        "main.py",
        "stuff.py",
    ],
    imports = [""],
    main = "main.py",
    python_version = "PY3",
    srcs_version = "PY3",
    deps = [],
)
