load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "apply_changes",
    srcs = ["main.go"],
    importpath = "github.com/thundergoler/bazel-linting-system",
    visibility = ["//visibility:public"],
    deps = [],
)
